In [4]:
from sklearn.tree import DecisionTreeClassifier
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, f1_score, precision_score, recall_score
df = pd.read_csv('CSV/loan_approval.csv')
df

,Age,Income,CreditScore,LoanAmount,Dependents,Education,SelfEmployed,PropertyArea,PreviousLoans,LoanApproved
0,25,35000.0,620,120000.0,0,Graduate,No,Urban,1,No
1,42,72000.0,780,200000.0,2,Graduate,No,Semiurban,0,Yes
2,35,58000.0,690,150000.0,1,Graduate,Yes,Rural,2,Yes
3,28,26000.0,590,100000.0,0,Not Graduate,No,Urban,1,No
4,50,85000.0,810,250000.0,3,Graduate,No,Semiurban,0,Yes
5,31,46000.0,640,130000.0,1,Graduate,Yes,Rural,1,No
6,39,67000.0,730,180000.0,2,Graduate,No,Urban,0,Yes
7,29,31000.0,610,110000.0,0,Not Graduate,No,Rural,2,No
8,45,79000.0,800,230000.0,2,Graduate,No,Semiurban,0,Yes
9,33,52000.0,675,145000.0,1,Graduate,Yes,Urban,1,Yes
10,36,NaN,710,170000.0,2,Graduate,No,Urban,0,Yes
11,42,72000.0,780,200000.0,2,Graduate,No,Semiurban,0,Yes
12,27,28000.0,600,NaN,0,Not Graduate,No,Rural,1,No

In [5]:
df.head()

,Age,Income,CreditScore,LoanAmount,Dependents,Education,SelfEmployed,PropertyArea,PreviousLoans,LoanApproved
0,25,35000.0,620,120000.0,0,Graduate,No,Urban,1,No
1,42,72000.0,780,200000.0,2,Graduate,No,Semiurban,0,Yes
2,35,58000.0,690,150000.0,1,Graduate,Yes,Rural,2,Yes
3,28,26000.0,590,100000.0,0,Not Graduate,No,Urban,1,No
4,50,85000.0,810,250000.0,3,Graduate,No,Semiurban,0,Yes

In [6]:
df['Income'].fillna(df['Income'].median(), inplace=True)

df['LoanAmount'].fillna(df['LoanAmount'].median(), inplace=True)
df.duplicated()
df.drop_duplicates(inplace=True)
df = pd.get_dummies(df, columns = ['Education', 'SelfEmployed', 'PropertyArea'], drop_first = True)
X = df.drop(columns=['LoanApproved'])
y = df['LoanApproved']
Xtrain, Xtest, ytrain, ytest = train_test_split(X, y, test_size=0.2, random_state=42)
model1 = DecisionTreeClassifier(criterion='entropy').fit(Xtrain, ytrain)
ypred1 = model1.predict(Xtest)
print(accuracy_score(ytest, ypred1))
TN, FP, FN, TP = confusion_matrix(ytest, ypred1).ravel()
recall1 = TP / (TP + FN)
specificity1 = TN / (TN + FP)
precision1 = TP / (TP + FP) 
print(recall1)
print(precision1)
print((2 * precision1 * recall1)/(precision1 + recall1))

0.6666666666666666
0.5
1.0
0.6666666666666666