In [94]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_squared_error, accuracy_score
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings('ignore')

In [95]:
df = pd.read_csv('CSV/car data.csv')
df

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0
...,...,...,...,...,...,...,...,...,...
296,city,2016,9.50,11.60,33988,Diesel,Dealer,Manual,0
297,brio,2015,4.00,5.90,60000,Petrol,Dealer,Manual,0
298,city,2009,3.35,11.00,87934,Petrol,Dealer,Manual,0
299,city,2017,11.50,12.50,9000,Diesel,Dealer,Manual,0
300,brio,2016,5.30,5.90,5464,Petrol,Dealer,Manual,0

In [96]:
df['Age_car'] = 2023 - df['Year']
df

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner,Age_car
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0,9
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0,10
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0,6
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0,12
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0,9
...,...,...,...,...,...,...,...,...,...,...
296,city,2016,9.50,11.60,33988,Diesel,Dealer,Manual,0,7
297,brio,2015,4.00,5.90,60000,Petrol,Dealer,Manual,0,8
298,city,2009,3.35,11.00,87934,Petrol,Dealer,Manual,0,14
299,city,2017,11.50,12.50,9000,Diesel,Dealer,Manual,0,6
300,brio,2016,5.30,5.90,5464,Petrol,Dealer,Manual,0,7

In [97]:
from sklearn.linear_model import LinearRegression

df = pd.get_dummies(df, columns = ['Fuel_Type','Seller_Type','Transmission'], drop_first=True)
df

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Owner,Age_car,Fuel_Type_Diesel,Fuel_Type_Petrol,Seller_Type_Individual,Transmission_Manual
0,ritz,2014,3.35,5.59,27000,0,9,False,True,False,True
1,sx4,2013,4.75,9.54,43000,0,10,True,False,False,True
2,ciaz,2017,7.25,9.85,6900,0,6,False,True,False,True
3,wagon r,2011,2.85,4.15,5200,0,12,False,True,False,True
4,swift,2014,4.60,6.87,42450,0,9,True,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...
296,city,2016,9.50,11.60,33988,0,7,True,False,False,True
297,brio,2015,4.00,5.90,60000,0,8,False,True,False,True
298,city,2009,3.35,11.00,87934,0,14,False,True,False,True
299,city,2017,11.50,12.50,9000,0,6,True,False,False,True
300,brio,2016,5.30,5.90,5464,0,7,False,True,False,True

In [98]:
y = df['Selling_Price']
X = df.drop(columns = ['Car_Name','Year','Selling_Price','Present_Price','Owner'])

Xtrain, Xtest, ytrain, ytest = train_test_split(X, y, test_size=0.2, random_state=42)

model = LinearRegression().fit(Xtrain, ytrain)
ypred = model.predict(Xtest)

print(model.intercept_)
print(model.coef_)
print(mean_squared_error(ytest, ypred))
print(r2_score(ytest, ypred))

print(model.predict([[55000, 18, 0, 1, 1, 1 ]]))
print(df.iloc[5])
print(model.predict([[2071, 5, 1, 0, 0, 1]]))

10.888445135748391
[-4.48042783e-06 -2.79387747e-01  6.40927579e+00  1.24649346e+00
 -4.11102502e+00 -4.80303386e+00]
9.418108720809975
0.5911495663366259
[-2.05452326]
Car_Name                  vitara brezza
Year                               2018
Selling_Price                      9.25
Present_Price                      9.83
Kms_Driven                         2071
Owner                                 0
Age_car                               5
Fuel_Type_Diesel                   True
Fuel_Type_Petrol                  False
Seller_Type_Individual            False
Transmission_Manual                True
Name: 5, dtype: object
[11.08846936]

In [99]:
# Q16

df = pd.read_csv('CSV/insurance.csv')
df

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [100]:
df = pd.get_dummies(df, columns = ['sex', 'smoker', 'region'])

In [101]:
y = df['charges']
X = df.drop(columns = ['charges'])

In [102]:
Xtrain, Xtest, ytrain, ytest = train_test_split(X, y, test_size = 0.2, random_state=42)

In [103]:
model = LinearRegression().fit(Xtrain, ytrain)
ypred = model.predict(Xtest)
print(model.coef_)
print(model.intercept_)
print(mean_squared_error(ytest, ypred))

[ 2.56975706e+02  3.37092552e+02  4.25278784e+02  9.29584582e+00
 -9.29584582e+00 -1.18255644e+04  1.18255644e+04  4.59585244e+02
  8.89079180e+01 -1.98279052e+02 -3.50214110e+02]
-574.5357125102
33596915.85136147

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_squared_error, accuracy_score
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
import warnings
warnings.filterwarnings('ignore')

df = pd.read_csv('CSV/winequalityN.csv')
df

df = pd.get_dummies(df, drop_first=True)
df

df.isnull().sum()


df.fillna(df.mean(), inplace=True)
# df[df['fixed acidity'].isnull() == True]
# df.iloc[17]
# df['pH'].mean() # np.float64(3.218395499383477)
# df[df['pH'].isnull() == 1] # index 54, 139, 440, 587

# df.iloc[[54, 139, 440, 587]]
# df.mean()

df.isnull().sum()

y = df['quality']
X = df.drop(columns = ['quality'])

Xtrain, Xtest, ytrain, ytest = train_test_split(X, y, test_size=0.2, random_state=42)

model = LinearRegression().fit(Xtrain, ytrain)
ypred = model.predict(Xtest)

print(model.intercept_)
print(model.coef_)
print(r2_score(ytest, ypred))
print(mean_squared_error(ytest, ypred))

print(model.predict([[8, 0.4, 0.4, 15, 0.048, 40, 150, 0.99, 3, 0.45, 10.5, 0]]))

In [44]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
import pandas as pd

In [45]:
df = pd.read_csv('CSV/Fish.csv')
df

    Species  Weight  Length1  Length2  Length3   Height   Width
0     Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1     Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2     Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3     Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4     Bream   430.0     26.5     29.0     34.0  12.4440  5.1340
..      ...     ...      ...      ...      ...      ...     ...
154   Smelt    12.2     11.5     12.2     13.4   2.0904  1.3936
155   Smelt    13.4     11.7     12.4     13.5   2.4300  1.2690
156   Smelt    12.2     12.1     13.0     13.8   2.2770  1.2558
157   Smelt    19.7     13.2     14.3     15.2   2.8728  2.0672
158   Smelt    19.9     13.8     15.0     16.2   2.9322  1.8792

[159 rows x 7 columns]

In [46]:
X = df.drop(columns = ['Species'])
y = df['Species']

In [49]:
Xtrain, Xtest, ytrain, ytest = train_test_split(X, y, test_size=0.2, random_state=42)
model = KNeighborsClassifier(n_neighbors = 5).fit(Xtrain, ytrain)
ypred = model.predict(Xtest)
print(accuracy_score(ytest, ypred))
print(df.iloc[0]['Species'])
print(model.predict([[242, 23.2, 25.4, 30.0, 11.52, 4.02]]))

0.625
Bream
['Perch']

In [31]:
ytest

78         Perch
155        Smelt
128         Pike
55     Whitefish
94         Perch
29         Bream
147        Smelt
51         Roach
98         Perch
141         Pike
19         Bream
60     Whitefish
15         Bream
65        Parkki
24         Bream
30         Bream
126        Perch
101        Perch
96         Perch
16         Bream
151        Smelt
18         Bream
12         Bream
9          Bream
31         Bream
125        Perch
95         Perch
56     Whitefish
145        Smelt
152        Smelt
135         Pike
76         Perch
Name: Species, dtype: object

In [53]:
df = pd.DataFrame({
    'Movie': ['M1','M2','M3','M4','M5','M6'],
    'Duration': [150, 120, 90, 100, 140, 95],
    'Level': [9,8,2,3,7,4],
    'Type': ['Action','Action','Comedy','Comedy','Action','Comedy']
})

X = df.drop(columns = ['Movie','Type'])
y = df['Type']

Xtrain, Xtest, ytrain, ytest = train_test_split(X, y, test_size=0.2, random_state=42)
model = KNeighborsClassifier(n_neighbors = 3).fit(Xtrain, ytrain)
ypred = model.predict(Xtest)
print(model.predict([[110, 6]]))
print(accuracy_score(ytest, ypred))

['Comedy']
0.0